train_env:
  type: 'src.gym_env.socket_plug.socket_plug_vec:SocketPlugVecEnv'
  kwargs:
    env_pr: "@pr"
    subenv_mid_name : "#"
    subenv_range: [0, 5]

    env_init_pos_min : [-10, -10, 5, -1, -1, -5]
    env_init_pos_max : [10, 10, 15, 1, 1, 5]
    env_max_steps : 20
    env_action_noise: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

    obs_type : 'depth'
    obs_depth_range: [0, 0.010]
    obs_process: "@ext_trans"

  wrapper:
    -
      type: 'src.sb3.vec_wrap:NetFeatObsWrapper'
      kwargs:
        net: "@backbone"
        feat_dim: 1280
      
eval_env:
  type: 'src.gym_env.socket_plug.socket_plug_vec:SocketPlugVecEnv'
  kwargs:
    env_pr: "@pr"
    subenv_mid_name : "#"
    subenv_range: [0, 5]

    env_init_pos_min : [-10, -10, 5, -1, -1, -5]
    env_init_pos_max : [10, 10, 15, 1, 1, 5]
    env_max_steps : 20
    env_action_noise: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

    obs_type : 'depth'
    obs_depth_range: [0, 0.010]
    obs_process: "@ext_trans"

  wrapper:
    -
      type: 'src.sb3.vec_wrap:NetFeatObsWrapper'
      kwargs:
        net: "@backbone"
        feat_dim: 1280

model:
  type: 'stable_baselines3:SAC'
  kwargs:
    policy: "MlpPolicy"
    policy_kwargs: 
      net_arch: [128]

    batch_size: 256
    learning_rate: 0.00644
    buffer_size: 5000
    learning_starts: 0

    train_freq: 1
    gradient_steps: 4

    gamma: 0.9
    tau: 0.1

trial:
  total_timesteps: 10000

  meta_manual_seed: 0
  meta_exp_root: "runs/socket_plug/ext_sac_raw"
  meta_exp_name: "trial"

  eval_freq: 500
  eval_num_episodes: 50
  eval_pruner_warmup_ratio: 0.7

  tb_record_episodes: 5
  tb_record_flag: 'ALL'
