train_env:
  type: "stable_baselines3.common.env_util:make_vec_env"
  kwargs:
    env_id: "Pendulum-v1"
    n_envs: 4
eval_env: ~

model:
  type: 'stable_baselines3:SAC'
  kwargs:
    policy: "MlpPolicy"
    policy_kwargs: 
      net_arch: "${sample.net_arch}"

    batch_size: "${sample.batch_size}"
    learning_rate: "${sample.learning_rate}"
    buffer_size: "${sample.buffer_size}"
    learning_starts: "${sample.learning_starts}"

    train_freq: "${sample.train_freq}"
    gradient_steps: "${sample.gradient_steps}"

    gamma: 0.9
    tau: "${sample.tau}"

trial:
  total_timesteps: 10000

  meta_manual_seed: 0
  meta_exp_root: "runs/example/pendulum"
  meta_exp_name: "trial"

  eval_freq: 2500
  eval_num_episodes: 50
  eval_pruner_warmup_ratio: 0.7

  tb_record_episodes: 5
  tb_record_flag: 'ALL'
  tb_record_last_only: True