train_env:
  type: "src.gym_env.plane_box.corner:CornerEnv"
  kwargs:
    env_pr: "@pr"
    subenv_mid_name : "#"
    subenv_range: [0, 4]

    obs_trans: "@corner_ext_trans"
    obs_source: "depth"

    env_init_box_pos_range: [
        [-25, -25, 15, -2, -2, -5],
        [25, 25, 35, 2, 2, 5]
    ]
    env_init_vis_pos_range: [
        [-5, -5, -5, -2, -2, -5],
        [5, 5, 5, 2, 2, 5]
    ]
    env_action_noise: [
      0.5, 0.5, 0.5, 0.1, 0.1, 0.1
    ]
    env_vis_persp_deg_disturb: 1
    env_movbox_height_offset_range: [-0.03, 0.02]

    env_movebox_center_err: [
        [-5, -5, -5, 0, 0, -5],
        [5, 5, 5, 0, 0, 5]
    ]

    env_reward_fn: "@reward_dist_fn"
    act_unit: [5, 5, 5, 1, 1, 1]

    corner_plane_height_offset_range: [-0.03, 0.03]
    env_tolerance_offset: -0.005

    env_is_complexity_progression: False

  wrapper: 
    -
      type: 'src.sb3.vec_wrap:NetFeatObsWrapper'
      kwargs:
        "@net": 
          type: "make_backbone"
          kwargs:
            path: "runs/done/corner_ext/best.pth"
        feat_dim: 1280

eval_env:
  type: "src.gym_env.plane_box.corner:CornerEnv"
  kwargs:
    env_pr: "@pr"
    subenv_mid_name : "#"
    subenv_range: [4, 6]

    obs_trans: "@corner_ext_trans"
    obs_source: "depth"

    env_init_box_pos_range: [
        [-25, -25, 15, -2, -2, -5],
        [25, 25, 35, 2, 2, 5]
    ]
    env_init_vis_pos_range: [
        [-5, -5, -5, -2, -2, -5],
        [5, 5, 5, 2, 2, 5]
    ]
    env_action_noise: [
      0.5, 0.5, 0.5, 0.1, 0.1, 0.1
    ]
    env_vis_persp_deg_disturb: 1
    env_movbox_height_offset_range: [-0.03, 0.02]

    env_movebox_center_err: [
        [-5, -5, -5, 0, 0, -5],
        [5, 5, 5, 0, 0, 5]
    ]

    env_reward_fn: "@reward_dist_fn"
    act_unit: [5, 5, 5, 1, 1, 1]

    corner_plane_height_offset_range: [-0.03, 0.03]
    env_tolerance_offset: -0.005

    env_is_complexity_progression: False

  wrapper: 
    -
      type: 'src.sb3.vec_wrap:NetFeatObsWrapper'
      kwargs:
        "@net": 
          type: "make_backbone"
          kwargs:
            path: "runs/done/corner_ext/best.pth"
        feat_dim: 1280

model:
  type: stable_baselines3:SAC
  kwargs:
    policy: MlpPolicy
    policy_kwargs:
      net_arch:
      - 256
    batch_size: 512
    learning_rate: 0.00062
    buffer_size: 20000
    learning_starts: 0
    train_freq: 16
    gradient_steps: 32
    gamma: 0.9
    tau: 0.1
trial:
  total_timesteps: 30000
  meta_manual_seed: 0
  meta_exp_root: runs/done/corner_ply/sac_normal
  meta_exp_name: trial
  eval_freq: 2500
  eval_num_episodes: 50
  eval_pruner_warmup_ratio: 0.7
  tb_record_episodes: 5
  tb_record_flag: ALL
  meta_object_path: runs/done/corner_ply/sac_normal
